// =================================================================================
// FILE: src/pages/TestimoniosPage.jsx
// =================================================================================
import React from 'react';
import  StarIcon  from '../components/icons/StarIcon'; // Ejemplo
const TestimoniosPage = () => {
    const testimonials = [ { name: 'Lucía M.', treatment: 'Hollywood Peel', quote: 'Me sentía opaca, como si mi cara no tuviera vida. El Hollywood Peel me devolvió la luz que creía perdida. La atención en DermicaPro es de primera, te hacen sentir muy cómoda.', rating: 5 }, { name: 'Javier R.', treatment: 'Eliminación de Tatuaje', quote: 'Tenía un tatuaje del que me arrepentía mucho y me daba vergüenza. El proceso con Pico Láser fue más rápido de lo que esperaba. Gracias por la paciencia y el profesionalismo.', rating: 5 }, { name: 'Sofía P.', treatment: 'Hifu 12D', quote: 'La flacidez me hacía sentir mayor de lo que soy. Los resultados del Hifu son sorprendentes. Noto mi rostro mucho más definido y firme. Lo recomiendo totalmente.', rating: 5 }, { name: 'Mateo L.', treatment: 'Enzimas Recombinantes', quote: 'Odiaba mi papada en las fotos. Tenía dudas sobre las enzimas, pero el resultado ha sido fantástico. Un cambio notorio sin cirugía.', rating: 4 }, { name: 'Isabella C.', treatment: 'Micropigmentación de Cejas', quote: 'Mis cejas eran mi mayor inseguridad. Ahora están perfectas, muy naturales. El diseño fue totalmente personalizado. ¡Estoy feliz!', rating: 5 }, ];
    return ( <div className="bg-gray-50 pt-24 pb-16 animate-fade-in"> <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"> <div className="text-center mb-12"> <h1 className="text-4xl font-extrabold text-gray-900 sm:text-5xl">Ellas también se sentían como tú. Hoy sonríen con confianza.</h1> <p className="mt-4 text-xl text-gray-600">Lee las historias de quienes, como tú, decidieron dar el paso y confiaron en nosotros.</p> </div> <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8"> {testimonials.map((testimonial, index) => ( <div key={index} className="bg-white p-8 rounded-lg shadow-md flex flex-col"> <div className="flex items-center mb-4"> {[...Array(testimonial.rating)].map((_, i) => <StarIcon key={i} className="w-5 h-5 text-[#ea899a]" />)} {[...Array(5 - testimonial.rating)].map((_, i) => <StarIcon key={i} className="w-5 h-5 text-gray-300" />)} </div> <blockquote className="text-gray-600 italic flex-grow">"{testimonial.quote}"</blockquote> <div className="mt-4 pt-4 border-t border-gray-200"> <p className="font-bold text-gray-900">{testimonial.name}</p> <p className="text-sm text-[#ea899a]">{testimonial.treatment}</p> </div> </div> ))} </div> </div> </div> );
};

export default TestimoniosPage;
